apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name:  grafana-service
  labels: 
    app: grafana
spec:
  selector:
    app:  grafana
  ports:
  - name:  grafana-port
    port:  80
    targetPort:  3000
  type: LoadBalancer