apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
  labels: 
    app: prometheus
rules:
- apiGroups:
  - networking.k8s.io
  resources: 
  - ingress
  verbs: 
  - get 
  - list 
  - watch
- apiGroups: [""]
  resources: 
  - nodes
  - nodes/metrics
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch 
- nonResourceURLs:
  - /metrics
  verbs: 
  - get 

