kind: Service
apiVersion: v1
metadata:
  name:  node-exporter-service
  namespace: monitoring
  labels: 
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
spec:
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
  ports:
  - name: node-exporter
    port:  9100
    targetPort:  9100
  clusterIP: None